{% set name = "inkex" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/inkex-{{ version }}.tar.gz
  sha256: 2f9803154806ebae8a40b33ef2c691806a472857adc90303eaa32482bd8c19ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - pygobject >=3.36
    - pyserial >=3.4.0,<4.0.0
    - lxml >=4.5.0,<6.0.0
    - numpy >=1.21.2,<2.0.0
    - pillow >=7.0.0
    - scour >=0.37.0,<0.38.0
    - packaging >=20.3
    - pyparsing >=3.0.9
    - cssselect >=1.2.0,<2.0.0
    - tinycss2 >=1.0.1,<2.0.0

test:
  imports:
    - inkex
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/inkex
  summary: Python extensions for Inkscape core, separated out from main repository.
  license: GPL-2.0-or-later
  license_file: LICENSE.txt
  dev_url: https://gitlab.com/inkscape/extensions

extra:
  recipe-maintainers:
    - anjos
